# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/

name: Colab Tests (nightly)

on:
  schedule:
    - cron: "0 10 * * *" # 10am UTC (3am PST)

  workflow_dispatch:  # Allow manual triggers

jobs:
  run-colabs-nightly:
    name: Run Colabs Python Nightly
    run: |
      python -m pip install --upgrade pip
      python -m pip install papermill
      python -m pip install tensorflow-cpu
      python -m pip install ipykernel
      python -m pip install jupyter
      python -m pip install matplotlib
      papermill colabs/getting_started.ipynb /tmp/out -k python3 -p visualize_model 0
